# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.1
    - extra-android-m2repository
    - extra-android-support

before_script:
  - touch bintray.properties

script:
  - bash ./gradlew :app:assembleDebug

notifications:
  email:
    - xz4214@gmail.com

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
